name: agent
downdir: /Users/xiao/download
log: /Users/xiao/Go/src/github.com/xtfly/gofd/config/log.xml
net:
    ip: 127.0.0.1
    mgntPort: 45010
    dataPort: 45011
    #tls:
    #    cert: /Users/xiao/server.crt
    #    key: /Users/xiao/server.key
auth:
    username: gofd
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    cacheSize: 50 # unit is MB
    maxActive: 10