name: client
downdir: /Users/xiao/download
log:
    level: INFO
net:
    ip: 127.0.0.1
    mgntPort: 45010
    dataPort: 45011
    tls:
        cert: /Users/xiao/server.cert
        key: /Users/xiao/server.key
auth:
    username: gofd
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    cacheSize: 50 # unit is MB
    maxActive: 10