name: client
downdir: /Users/xiao
log:
    level: INFO
net:
    ip: 127.0.0.1
    mgntPort: 45010
    dataPort: 45011
    tls:
        cert: /Users/xiao/gop2p.cert
        key: /Users/xiao/gop2p.key
auth:
    username: gop2p
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    speed: 10