name: server
log:
    level: INFO
net:
    ip: 127.0.0.1
    mgntPort: 45000
    dataPort: 45001
    clientMgntPort: 45010
    clientDataPort: 45011
    tls:
        cert: /Users/xiao/server.cert
        key: /Users/xiao/server.key
auth:
    username: gofd
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    speed: 10  # unit is MB
    cacheSize: 50 # unit is MB
    maxActive: 10