name: server
log:
    level: INFO
net:
    ip: 127.0.0.1
    mgntPort: 45000
    dataPort: 45001
    tls:
        cert: /Users/xiao/gop2p.cert
        key: /Users/xiao/gop2p.key
auth:
    username: gop2p
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    speed: 10
    cacheSize: 50
    maxActive: 10