name: server
log:
    level: INFO
net:
    ip: 127.0.0.1
    mgntPort: 45001
    dataPort: 45002
    tls:
        cert: /Users/xiao/gop2p.cert
        key: /Users/xiao/gop2p.key
auth:
    username: gop2p
    passowrd: AFDAFAFEWFAGAGAGAG
contorl:
    upspeed: 10M
    downspeed: 10M