name: server
log: /Users/xiao/Go/src/github.com/xtfly/gofd/config/log.xml
net:
    ip: 127.0.0.1
    mgntPort: 45000
    dataPort: 45001
    agentMgntPort: 45010
    agentDataPort: 45011
    #tls:
    #    cert: /Users/xiao/server.crt
    #    key: /Users/xiao/server.key
auth:
    username: gofd
    passowrd: yrsK+2iiwPqecImH7obTUm1vhnvvQzFmYYiOz5oqaoc=
    factor: 9427e80d
    crc: 63F7
contorl:
    speed: 10  # unit is MB
    cacheSize: 50 # unit is MB
    maxActive: 10
